# Generated by Django 4.0.1 on 2022-03-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recollect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='course_id',
            new_name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
